# Generated by Django 5.2.6 on 2025-10-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0009_remove_user_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
